#include "StdAfx.h"
#include "OrganizationStructureInfoDemo.h"

OrganizationStructureInfoDemo::OrganizationStructureInfoDemo(void)
{
}


OrganizationStructureInfoDemo::~OrganizationStructureInfoDemo(void)
{
}

int OrganizationStructureInfoDemo::GetWholeOrganization( std::vector<ORG_NODE>* pNodes )
{
	ORG_NODE user1, user2, user3, user4, user5;
	user1.strName = "李丽";
	user1.iNodeId = 13;
	user1.iParentID = 2;
	user1.iLevel = 3;
	user1.iNodeType = 1;
	

	user2.iNodeId = 14;
	user2.strName = "王磊";
	user2.iParentID = 6;
	user2.iLevel = 4;
	user2.iNodeType = 1;

	user3.iNodeId = 15;
	user3.strName = "李华";
	user3.iParentID = 7;
	user3.iLevel = 4;
	user3.iNodeType = 1;

	user4.iNodeId = 16;
	user4.strName = "乐乐";
	user4.iParentID = 10;
	user4.iLevel = 3;
	user4.iNodeType = 1;

	user5.iNodeId = 17;
	user5.strName = "jack";
	user5.iParentID = 11;
	user5.iLevel = 3;
	user5.iNodeType = 1;

	//+-----------------------0
	ORG_NODE root1;
	root1.iLevel = 0;
	root1.iNodeId = 0;
	root1.iNodeType = 0;
	root1.iParentID = -1;
	root1.strName = "卡拉巴斯暗杀公司";
		//+-------------------------------1
		ORG_NODE node1, node2, node3, node4;
		node1.iLevel = 1;
		node1.iNodeId = 1;
		node1.iNodeType = 0;
		node1.iParentID = 0;
		node1.strName = "客户搜索部";
			//+------------------------------------2
			ORG_NODE node1_0, node1_1;
			node1_0.iLevel = 2;
			node1_0.iNodeId = 2;
			node1_0.iNodeType = 0;
			node1_0.iParentID = 1;
			node1_0.strName = "仇杀客户部";
			//+------------------------------------2
			node1_1.iLevel = 2;
			node1_1.iNodeId = 3;
			node1_1.iNodeType = 0;
			node1_1.iParentID = 1;
			node1_1.strName = "政敌客户部";
		//+-------------------------------1
		node2.iLevel = 1;
		node2.iNodeId = 4;
		node2.iNodeType = 0;
		node2.iParentID = 0;
		node2.strName = "策划部";
			//+------------------------------------2
			ORG_NODE node2_0;
			node2_0.iLevel = 2;
			node2_0.iNodeId = 5;
			node2_0.iNodeType = 0;
			node2_0.iParentID = 4;
			node2_0.strName = "暗杀过程策划中心";
				//+----------------------------------------3
				ORG_NODE node2_0_0, node2_0_1, node2_0_2;
				node2_0_0.iLevel = 3;
				node2_0_0.iNodeId = 6;
				node2_0_0.iNodeType = 0;
				node2_0_0.iParentID = 5;
				node2_0_0.strName = "暗杀路线策划部";
				//+----------------------------------------3
				node2_0_1.iLevel = 3;
				node2_0_1.iNodeId = 7;
				node2_0_1.iNodeType = 0;
				node2_0_1.iParentID = 5;
				node2_0_1.strName = "现场清理扫尾部";
				//+----------------------------------------3
				node2_0_2.iLevel = 3;
				node2_0_2.iNodeId = 8;
				node2_0_2.iNodeType = 0;
				node2_0_2.iParentID = 5;
				node2_0_2.strName = "暗杀过程模拟部";
		//+----------------------------1
		node3.iLevel = 1;
		node3.iNodeId = 9;
		node3.iNodeType = 0;
		node3.iParentID = 0;
		node3.strName = "执行部";
			//+-----------------------------------2
			ORG_NODE node3_0, node3_1;
			node3_0.iLevel = 2;
			node3_0.iNodeId = 10;
			node3_0.iNodeType = 0;
			node3_0.iParentID = 9;
			node3_0.strName = "见习杀手部";
			//+-----------------------------------2
			node3_1.iLevel = 2;
			node3_1.iNodeId = 11;
			node3_1.iNodeType = 0;
			node3_1.iParentID = 9;
			node3_1.strName = "专业杀手部";
		//+----------------------------1
		node4.iLevel = 1;
		node4.iNodeId = 12;
		node4.iNodeType = 0;
		node4.iParentID = 0;
		node4.strName = "分赃部";

	pNodes->push_back(root1);
	pNodes->push_back(node1);
	pNodes->push_back(node1_0);
	pNodes->push_back(node1_1);
	pNodes->push_back(node2);
	pNodes->push_back(node2_0);
	pNodes->push_back(node2_0_0);
	pNodes->push_back(node2_0_1);
	pNodes->push_back(node2_0_2);
	pNodes->push_back(node3);
	pNodes->push_back(node3_0);
	pNodes->push_back(node3_1);
	pNodes->push_back(node4);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	/*pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);
	pNodes->push_back(user1);
	pNodes->push_back(user2);
	pNodes->push_back(user3);
	pNodes->push_back(user4);
	pNodes->push_back(user5);*/
	return 0;
}

int OrganizationStructureInfoDemo::GetDepatment( int iID, std::vector<ORG_NODE>* pNodes )
{
	return 0;
}
